### ISSUE TITLE
Module build failed: SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by vital101** [webpack-contrib/coffee-loader#46]
I'm trying to get `coffee-loader` working with an older project, but for some reason I can't get it to work with even a simple test file. I'm not sure where to go from here and any pointers would be appreciated.

#### The error

    > $ npm run build                                                                                                                           ⬡ 4.4.4 [±webpack ●●]

    > owl@0.1.0 build /Users/jack/repos/owl
    > webpack

    Hash: d7c867d7bcd8af11795b
    Version: webpack 3.6.0
    Time: 58ms
        Asset     Size  Chunks             Chunk Names
    bundle.js  4.76 kB       0  [emitted]  main
    [0] ./test.coffee 2.28 kB {0} [built] [failed] [1 error]

    ERROR in ./test.coffee
    Module build failed: SyntaxError: Unexpected token =
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:373:25)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at Object.<anonymous> (/Users/jack/repos/owl/node_modules/coffee-loader/index.js:5:14)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at loadLoader (/Users/jack/repos/owl/node_modules/webpack/node_modules/loader-runner/lib/loadLoader.js:13:17)
        at iteratePitchingLoaders (/Users/jack/repos/owl/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at runLoaders (/Users/jack/repos/owl/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
        at NormalModule.doBuild (/Users/jack/repos/owl/node_modules/webpack/lib/NormalModule.js:182:3)
        at NormalModule.build (/Users/jack/repos/owl/node_modules/webpack/lib/NormalModule.js:275:15)
        at Compilation.buildModule (/Users/jack/repos/owl/node_modules/webpack/lib/Compilation.js:149:10)
        at /Users/jack/repos/owl/node_modules/webpack/lib/Compilation.js:447:10
        at /Users/jack/repos/owl/node_modules/webpack/lib/NormalModuleFactory.js:241:5
        at /Users/jack/repos/owl/node_modules/webpack/lib/NormalModuleFactory.js:94:13
        at /Users/jack/repos/owl/node_modules/webpack/node_modules/tapable/lib/Tapable.js:268:11
        at NormalModuleFactory.<anonymous> (/Users/jack/repos/owl/node_modules/webpack/lib/CompatibilityPlugin.js:52:5)
        at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/jack/repos/owl/node_modules/webpack/node_modules/tapable/lib/Tapable.js:272:13)
        at /Users/jack/repos/owl/node_modules/webpack/lib/NormalModuleFactory.js:69:10
        at /Users/jack/repos/owl/node_modules/webpack/lib/NormalModuleFactory.js:194:7
        at nextTickCallbackWith0Args (node.js:420:9)
        at process._tickCallback (node.js:349:13)

#### test.coffee

    # Assignment:
    number   = 42
    opposite = true

    # Conditions:
    number = -42 if opposite

    # Functions:
    square = (x) -> x * x

    # Arrays:
    list = [1, 2, 3, 4, 5]

    # Objects:
    math =
    root:   Math.sqrt
    square: square
    cube:   (x) -> x * square x

    # Splats:
    race = (winner, runners...) ->
    print winner, runners

    # Existence:
    alert "I knew it!" if elvis?

    # Array comprehensions:
    cubes = (math.cube num for num in list)

#### webpack.config.js

    const path = require('path');

    module.exports = {
      entry: './test.coffee',
      output: {
        filename: 'bundle.js',
        path: path.resolve(__dirname, 'dist')
      },
      module: {
        rules: [
          {
            test: /\.css$/,
            use: [
              'style-loader',
              'css-loader'
            ]
          },
          {
            test: /\.coffee$/,
            use: [ 'coffee-loader' ]
          }
        ]
      }
    };

**Comment by Jascha-Sundaresan** [comment]
objects and splats need to be indented

```
# Objects:
math =
root:   Math.sqrt
  square: square
  cube:   (x) -> x * square x

# Splats:
race = (winner, runners...) ->
  print winner, runners
```

Coffeescript cares about whitespace

**Comment by michael-ciniawsky** [comment]
@Jascha-Sundaresan Thx 👍 

@vital101 See @Jascha-Sundaresan  answer and feel free to reopen if still regressions :)

**Comment by nguyenj** [comment]
I'm also getting the exact same error on a simple test:

```
// /webpack.config.js

const path = require('path')

module.exports = {
  entry: './src/index.js',

  output: {
    path: path.join(__dirname, 'dist'),
    filename: "[name].js"
  },

  module: {
    rules: [
      {
        test: /\.coffee$/,
        use: [
          {
            loader: 'coffee-loader',
            options: {
              sourceMaps: true
            }
          }
        ]
      },
    ]
  },

  resolve: {
    extensions: ['.coffee', '.js']
  }
}
```

```
# /src/index.coffee

require './test'
```

```
# /src/test.coffee

console.log 'testing'
```

**Comment by Nyxelio** [comment]
Coffeescript 2 seems to break the loader and downgrading to a 1.12.x version fixes this issue.

**Comment by nguyenj** [comment]
@Nyxelio Yeah I did that it all works now–I guess no dice on coffeescript v2.
